/*
  Builds astryx/graph.json — a knowledge graph of the 2one × Astryx library.
  Nodes = components (from the showcase gallery), the 2one rules that govern the
  re-skin, and the brand. Edges = uses (component→component, parsed from the
  showcase imports), governed_by, embodies. Generated from source so it never
  drifts. Read by the generic explorer in astryx/dev/graph.html (graph-main.ts).

  Run: npm run graph
*/
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const R = (p) => readFileSync(join(root, p), 'utf8')

const nodes = new Map()
const edges = []
const addNode = (id, type, label, extra = {}) => { if (!nodes.has(id)) nodes.set(id, { id, type, label, ...extra }) }
const addEdge = (source, target, type) => { if (nodes.has(source) && nodes.has(target)) edges.push({ source, target, type }) }
const compId = (n) => `component:${n}`

// ---- COMPONENT nodes (one per *Showcase in the gallery) + the core comps they import ----
const galleryDir = 'src/gallery'
const files = readdirSync(join(root, galleryDir)).filter((f) => f.endsWith('Showcase.tsx'))
const nameOf = (f) => f.replace(/Showcase\.tsx$/, '')
const importsOf = (src) => { const s = new Set(); for (const m of src.matchAll(/@astryxdesign\/core\/([A-Za-z0-9]+)/g)) s.add(m[1]); return s }

for (const f of files) addNode(compId(nameOf(f)), 'component', nameOf(f))
// a showcase may import other core components (Layout/Text/Button…) — add them too
for (const f of files) for (const c of importsOf(R(`${galleryDir}/${f}`))) addNode(compId(c), 'component', c)

// ---- USES edges: the demoed component uses each component its showcase imports ----
for (const f of files) {
  const subj = compId(nameOf(f))
  for (const c of importsOf(R(`${galleryDir}/${f}`))) if (c !== nameOf(f)) addEdge(subj, compId(c), 'uses')
}

// ---- RULE nodes (how the 2one re-skin is governed) ----
const rule = (id, label) => addNode(`rule:${id}`, 'rule', label)
rule('grayscale', 'Grayscale only — Astryx categorical hues desaturated to neutral')
rule('validation-only', 'danger/success are the only hues, reserved for validation')
rule('no-color-alone', 'Never convey state by colour alone (icon/text + colour)')
rule('a11y-audited', 'APCA-audited in light AND dark (npm run a11y)')
rule('satoshi-inter', 'Satoshi headings + Inter body, on every surface')
rule('theme-not-fork', 'Re-skin via the 2one theme — never fork Astryx component source')

// every component is governed by the always-on rules
for (const f of files) {
  const id = compId(nameOf(f))
  addEdge(id, 'rule:grayscale', 'governed_by')
  addEdge(id, 'rule:a11y-audited', 'governed_by')
}
// validation-carrying components also answer to the validation rules
for (const c of ['Badge', 'Banner', 'StatusDot', 'ProgressBar', 'Toast', 'Alert', 'FieldStatus', 'InlineNotification', 'Spinner']) {
  if (nodes.has(compId(c))) { addEdge(compId(c), 'rule:validation-only', 'governed_by'); addEdge(compId(c), 'rule:no-color-alone', 'governed_by') }
}

// ---- BRAND nodes + embodies ----
addNode('brand:mission', 'brand', '2one — structure in a changing tech environment')
addNode('brand:voice', 'brand', 'Voice: Minimalistic · Contemporary · Empathetic · Bold')
for (const id of ['grayscale', 'validation-only', 'no-color-alone', 'satoshi-inter']) addEdge('brand:voice', `rule:${id}`, 'embodies')
for (const id of ['a11y-audited', 'theme-not-fork']) addEdge('brand:mission', `rule:${id}`, 'embodies')

// ---- write ----
const nodeArr = [...nodes.values()]
const stats = {
  nodes: nodeArr.length,
  edges: edges.length,
  by_node_type: nodeArr.reduce((a, n) => ((a[n.type] = (a[n.type] || 0) + 1), a), {}),
  by_edge_type: edges.reduce((a, e) => ((a[e.type] = (a[e.type] || 0) + 1), a), {}),
}
writeFileSync(join(root, 'graph.json'), JSON.stringify({
  name: '2one × Astryx knowledge graph',
  description: 'Astryx components (nodes) and how they compose (uses), governed by the 2one re-skin rules and brand. Generated by scripts/build-graph.mjs.',
  stats, nodes: nodeArr, edges,
}, null, 2) + '\n')
console.log(`astryx/graph.json — ${stats.nodes} nodes, ${stats.edges} edges`)
console.log('  nodes:', JSON.stringify(stats.by_node_type))
console.log('  edges:', JSON.stringify(stats.by_edge_type))
