// Auto-generated — Astryx components grouped into sections (mirrors the shadcn showcase).
import type React from 'react'
import ButtonSC from './gallery/ButtonShowcase'
import ButtonGroupSC from './gallery/ButtonGroupShowcase'
import IconButtonSC from './gallery/IconButtonShowcase'
import ToggleButtonSC from './gallery/ToggleButtonShowcase'
import SegmentedControlSC from './gallery/SegmentedControlShowcase'
import LinkSC from './gallery/LinkShowcase'
import MoreMenuSC from './gallery/MoreMenuShowcase'
import KbdSC from './gallery/KbdShowcase'
import TextInputSC from './gallery/TextInputShowcase'
import TextAreaSC from './gallery/TextAreaShowcase'
import NumberInputSC from './gallery/NumberInputShowcase'
import CheckboxInputSC from './gallery/CheckboxInputShowcase'
import CheckboxListSC from './gallery/CheckboxListShowcase'
import RadioListSC from './gallery/RadioListShowcase'
import SwitchSC from './gallery/SwitchShowcase'
import SelectorSC from './gallery/SelectorShowcase'
import MultiSelectorSC from './gallery/MultiSelectorShowcase'
import SliderSC from './gallery/SliderShowcase'
import DateInputSC from './gallery/DateInputShowcase'
import DateRangeInputSC from './gallery/DateRangeInputShowcase'
import DateTimeInputSC from './gallery/DateTimeInputShowcase'
import TimeInputSC from './gallery/TimeInputShowcase'
import FileInputSC from './gallery/FileInputShowcase'
import TypeaheadSC from './gallery/TypeaheadShowcase'
import TokenizerSC from './gallery/TokenizerShowcase'
import FieldSC from './gallery/FieldShowcase'
import FieldStatusSC from './gallery/FieldStatusShowcase'
import FormLayoutSC from './gallery/FormLayoutShowcase'
import InputGroupSC from './gallery/InputGroupShowcase'
import TableSC from './gallery/TableShowcase'
import TreeListSC from './gallery/TreeListShowcase'
import ListSC from './gallery/ListShowcase'
import ItemSC from './gallery/ItemShowcase'
import MetadataListSC from './gallery/MetadataListShowcase'
import AvatarSC from './gallery/AvatarShowcase'
import AvatarGroupSC from './gallery/AvatarGroupShowcase'
import StatusDotSC from './gallery/StatusDotShowcase'
import BadgeSC from './gallery/BadgeShowcase'
import CardSC from './gallery/CardShowcase'
import ClickableCardSC from './gallery/ClickableCardShowcase'
import SelectableCardSC from './gallery/SelectableCardShowcase'
import TimestampSC from './gallery/TimestampShowcase'
import CodeSC from './gallery/CodeShowcase'
import CodeBlockSC from './gallery/CodeBlockShowcase'
import BlockquoteSC from './gallery/BlockquoteShowcase'
import CitationSC from './gallery/CitationShowcase'
import MarkdownSC from './gallery/MarkdownShowcase'
import CalendarSC from './gallery/CalendarShowcase'
import CarouselSC from './gallery/CarouselShowcase'
import ThumbnailSC from './gallery/ThumbnailShowcase'
import LightboxSC from './gallery/LightboxShowcase'
import OverflowListSC from './gallery/OverflowListShowcase'
import BannerSC from './gallery/BannerShowcase'
import ToastSC from './gallery/ToastShowcase'
import ProgressBarSC from './gallery/ProgressBarShowcase'
import SpinnerSC from './gallery/SpinnerShowcase'
import SkeletonSC from './gallery/SkeletonShowcase'
import EmptyStateSC from './gallery/EmptyStateShowcase'
import BreadcrumbsSC from './gallery/BreadcrumbsShowcase'
import TabListSC from './gallery/TabListShowcase'
import SideNavSC from './gallery/SideNavShowcase'
import TopNavSC from './gallery/TopNavShowcase'
import MobileNavSC from './gallery/MobileNavShowcase'
import CommandPaletteSC from './gallery/CommandPaletteShowcase'
import PowerSearchSC from './gallery/PowerSearchShowcase'
import DialogSC from './gallery/DialogShowcase'
import PopoverSC from './gallery/PopoverShowcase'
import TooltipSC from './gallery/TooltipShowcase'
import HoverCardSC from './gallery/HoverCardShowcase'
import ContextMenuSC from './gallery/ContextMenuShowcase'
import DropdownMenuSC from './gallery/DropdownMenuShowcase'
import AppShellSC from './gallery/AppShellShowcase'
import GridSC from './gallery/GridShowcase'
import CenterSC from './gallery/CenterShowcase'
import DividerSC from './gallery/DividerShowcase'
import AspectRatioSC from './gallery/AspectRatioShowcase'
import CollapsibleSC from './gallery/CollapsibleShowcase'
import ResizableSC from './gallery/ResizableShowcase'
import TextSC from './gallery/TextShowcase'
import HeadingSC from './gallery/HeadingShowcase'
import IconSC from './gallery/IconShowcase'

export const CATEGORIES = [
  { id: 'actions', title: "Actions", desc: "Buttons, toggles and action affordances.", items: [['Button', ButtonSC], ['ButtonGroup', ButtonGroupSC], ['IconButton', IconButtonSC], ['ToggleButton', ToggleButtonSC], ['SegmentedControl', SegmentedControlSC], ['Link', LinkSC], ['MoreMenu', MoreMenuSC], ['Kbd', KbdSC]] as [string, React.ComponentType][] },
  { id: 'inputs', title: "Inputs & Forms", desc: "Text, choice, date and file inputs plus form scaffolding.", items: [['TextInput', TextInputSC], ['TextArea', TextAreaSC], ['NumberInput', NumberInputSC], ['CheckboxInput', CheckboxInputSC], ['CheckboxList', CheckboxListSC], ['RadioList', RadioListSC], ['Switch', SwitchSC], ['Selector', SelectorSC], ['MultiSelector', MultiSelectorSC], ['Slider', SliderSC], ['DateInput', DateInputSC], ['DateRangeInput', DateRangeInputSC], ['DateTimeInput', DateTimeInputSC], ['TimeInput', TimeInputSC], ['FileInput', FileInputSC], ['Typeahead', TypeaheadSC], ['Tokenizer', TokenizerSC], ['Field', FieldSC], ['FieldStatus', FieldStatusSC], ['FormLayout', FormLayoutSC], ['InputGroup', InputGroupSC]] as [string, React.ComponentType][] },
  { id: 'data', title: "Data display", desc: "Tables, lists, cards, media and content.", items: [['Table', TableSC], ['TreeList', TreeListSC], ['List', ListSC], ['Item', ItemSC], ['MetadataList', MetadataListSC], ['Avatar', AvatarSC], ['AvatarGroup', AvatarGroupSC], ['StatusDot', StatusDotSC], ['Badge', BadgeSC], ['Card', CardSC], ['ClickableCard', ClickableCardSC], ['SelectableCard', SelectableCardSC], ['Timestamp', TimestampSC], ['Code', CodeSC], ['CodeBlock', CodeBlockSC], ['Blockquote', BlockquoteSC], ['Citation', CitationSC], ['Markdown', MarkdownSC], ['Calendar', CalendarSC], ['Carousel', CarouselSC], ['Thumbnail', ThumbnailSC], ['Lightbox', LightboxSC], ['OverflowList', OverflowListSC]] as [string, React.ComponentType][] },
  { id: 'feedback', title: "Feedback", desc: "Banners, toasts, progress and empty states.", items: [['Banner', BannerSC], ['Toast', ToastSC], ['ProgressBar', ProgressBarSC], ['Spinner', SpinnerSC], ['Skeleton', SkeletonSC], ['EmptyState', EmptyStateSC]] as [string, React.ComponentType][] },
  { id: 'navigation', title: "Navigation", desc: "Breadcrumbs, tabs, nav shells and search.", items: [['Breadcrumbs', BreadcrumbsSC], ['TabList', TabListSC], ['SideNav', SideNavSC], ['TopNav', TopNavSC], ['MobileNav', MobileNavSC], ['CommandPalette', CommandPaletteSC], ['PowerSearch', PowerSearchSC]] as [string, React.ComponentType][] },
  { id: 'overlays', title: "Overlays", desc: "Dialogs, popovers and menus.", items: [['Dialog', DialogSC], ['Popover', PopoverSC], ['Tooltip', TooltipSC], ['HoverCard', HoverCardSC], ['ContextMenu', ContextMenuSC], ['DropdownMenu', DropdownMenuSC]] as [string, React.ComponentType][] },
  { id: 'layout', title: "Layout", desc: "Page frame, grids and structural helpers.", items: [['AppShell', AppShellSC], ['Grid', GridSC], ['Center', CenterSC], ['Divider', DividerSC], ['AspectRatio', AspectRatioSC], ['Collapsible', CollapsibleSC], ['Resizable', ResizableSC]] as [string, React.ComponentType][] },
  { id: 'content', title: "Content", desc: "Typography and iconography.", items: [['Text', TextSC], ['Heading', HeadingSC], ['Icon', IconSC]] as [string, React.ComponentType][] },
]
